### PR TITLE
fix: flush pending hooks effects in rerender

### PR DESCRIPTION
**Pull request by aduth**
**What**:

Call preact/test-utils act which manages the same setupRerender behavior implemented previously in preact-testing-library, but also flushes any pending hook effects.

**Why**:

I had encountered an issue in one of my own projects using `@testing-library/preact-hooks` where calling hook's `setState` would not trigger a render, in a case where the state setter may be called asynchronously.

**How**:

This follows and defers to the internal [implementation of `preact/test-utils`'s `act` function](https://github.com/preactjs/preact/blob/134f65c6c8ec4107da30a82b348ce3c596da0c0e/test-utils/src/index.js#L18-L99), which also calls `setupRerender`'s resulting rerender function, but only after handling flushing behavior. The changes here effectively incorporate that behavior.

See also: https://github.com/preactjs/preact/pull/1437

**Checklist**:

- [ ] Documentation added (N/A)
- [x] Tests
- [ ] Typescript definitions updated (N/A)
- [x] Ready to be merged

### CODE REVIEW

**Comment by ombene** [comment]
I'm experiencing this issue as well, and likewise this fix seems to work well for me. Thanks @aduth! Maintainers: any update on this?

**Review by nickmccurdy — APPROVED** [review]

**Comment by mbradley36** [comment]
Is there any update on this? I am running in to this issue as well.

**Comment by parkjh** [comment]
@nickmccurdy Hello, I just wanted to ask if this pr is planned to be merged / released any time soon?

**Comment by bmarti44** [comment]
we're running into this issue as well - is there any additional verification we can do to help push this through?

**Comment by kentcdodds** [comment]
There are no active maintainers on this project. If anyone's willing to step up as an official committed maintainer and can present some trustworthy credentials (good OSS behavior in the past) then I'd be willing to give maintainer rights. Until then, I'm afraid there's just no bandwidth for maintaining this project.

**Comment by JoviDeCroock** [comment]
Hey @kentcdodds I don't mind taking over some of the maintenance on this project if you don't mind

**Comment by kentcdodds** [comment]
Thanks @JoviDeCroock! I'll get you added to the team right away.

**Review by JoviDeCroock — APPROVED** [review]

**Comment by kentcdodds** [comment]
Eek, I didn't realize this was on Travis. I'm afraid I don't think I have access to the travis stuff for this project. It may be that we first need to update the CI pipeline... I'm going to remove the required TravisCI check for now.

**Comment by kentcdodds** [comment]
I should add @JoviDeCroock that you don't need my permission or anything for this project at all. If you want to change the setup or whatever that's totally up to you. Like I said, I don't have the bandwidth to work on this project at the moment so feel free to take complete ownership over it. I appreciate you giving it some of your time and attention!

**Comment by JoviDeCroock** [comment]
@kentcdodds sorry to bother you but one last request could someone do a manual request of the git tag for 3.0.0 as we dropped node 10 support, however the semantic release was bugged. Fixed that in #54

**Comment by kentcdodds** [comment]
Happy to help. I don't understand what you're asking me to do though. Could you elaborate?

**Comment by JoviDeCroock** [comment]
This run created a tag on github but the publish failed https://github.com/testing-library/preact-testing-library/runs/6494824522?check_suite_focus=true - the fix however happens in a later commit so I can't just rerun it. This is a manual publish I assume

**Comment by kentcdodds** [comment]
Dang it. I always hate when semantic-release falls off the rails. I never know how to get it back going again. I'll look into it.

**Comment by kentcdodds** [comment]
Based on the error message from the latest build, it's not a manual publish we need:

> The current error message when publishing
> 
> npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

**Comment by kentcdodds** [comment]
Ok, so you're saying that if I do a manual publish of the package this should fix itself? Do you know what version I need to publish? (Sorry, I just don't have too much time to look into it).

**Comment by JoviDeCroock** [comment]
First and foremost sorry for the spam on your PR 😅 this [tag](https://github.com/testing-library/preact-testing-library/releases/tag/v3.0.0) should be ready to publish so going to that tag and running the build and then publish

**Comment by kentcdodds** [comment]
Actually, you should have publish rights anyway, so I added you to the npm org 👍

**Comment by aduth** [comment]
Glad to see this shipped! Thank you @kentcdodds and @JoviDeCroock for helping to keep this project maintained 🙂

**Pull request merged**
