### PR TITLE
fix: preact does not export Element

### PR DESCRIPTION
**Pull request by maxbeatty**
**What**: bug in types. preact does not export `Element`

**Why**: causing issues in TypeScript project (and errors with eslint)

**How**: remove type declaration and depend on global `Element`

**Checklist**:

- [ ] Documentation added
- [ ] Tests
- [x] Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
`Element` is exported by the JSX bindings only, is it found as a global when you remove the import?

**Comment by maxbeatty** [comment]
my project is using:
- "typescript": "^4.7.3",
- "preact": "^10.7.3",

with v3.2.1, I'm seeing this error:

```sh
❯ tsc
node_modules/@testing-library/preact/types/index.d.ts:3:41 - error TS2305: Module '"preact"' has no exported member 'Element'.

3 import { ComponentChild, ComponentType, Element } from 'preact'
```

downgrading to v3.1.2 fixes the error. I was also able to verify by manually removing the `Element` import.

to your point, maybe a more appropriate fix is something like:

```diff
- import { ComponentChild, ComponentType, Element } from 'preact'
+ import { ComponentChild, ComponentType, JSX } from 'preact'

export * from '@testing-library/dom'

export type RenderResult<Q extends Queries = typeof queries> = {
-  container: Element
+  container: JSX.Element
```

**Comment by JoviDeCroock** [comment]
if it compiles with it removed (and finds it globally) that's good for me as well but yeah if we can use `JSX.Element` could be more appropriate😅

**Comment by maxbeatty** [comment]
actually, I think this should be a global `Element` to satisfy [@testing-library/dom](https://github.com/testing-library/dom-testing-library/blob/11fc7731e5081fd0994bf2da84d688fdb592eda7/types/events.d.ts#L91)

```ts
import { render, fireEvent } from '@testing-library/preact';

// container is type Element
const { container } = render(<ExampleComponent />)

// fireEvent expects element to be Document | **Element** | Window | Node
fireEvent(container, new Event('example')
```

**Review by JoviDeCroock — APPROVED** [review]

**Pull request merged**
